### ISSUE TITLE
Tectonic biber docker image

### ISSUE THREAD

**Issue by WtfJoke** [PHPirates/travis-ci-latex-pdf#15]
I made a tectonic docker image with biber included (thanks to the work of #10 and @malramsay64 comment in https://github.com/tectonic-typesetting/tectonic/issues/53#issuecomment-404370890 and https://github.com/rekka/tectonic-docker).

The image can be found here: https://hub.docker.com/r/dxjoke/tectonic-docker/
My .travis.yml looks like this:
```

sudo: required
services: docker
script:
- docker pull dxjoke/tectonic-docker
- docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic --keep-intermediates --reruns 0 main.tex; biber main; tectonic main.tex"
deploy:
  provider: releases
  api_key:
    secure: [superlongapikey]
  file: main.pdf
  skip_cleanup: true
  on:
repo: [myrepo]
```

Its quite fast since all the long running tasks are bundled inside of the docker image. My tests using miniconda were terrible slow on each build.
Maybe you can test this as well and see if it works for you as well and include it in your repo. :)
