### ISSUE TITLE
TeXLive Travis CI (a contribution)

### ISSUE THREAD

**Issue by pablgonz** [PHPirates/travis-ci-latex-pdf#23]
Hello, first of all a million thanks for the tutorial, I would like to make a contribution. I have modified a little the example files that for `TeXLive`. 
In `texlive_install.sh` I have added a regular expression to read the file `texlive_packages`, now it is possible to place comments to have more clarity about what each package does.
```bash
#!/usr/bin/env sh

# Originally from https://github.com/latex3/latex3

# This script is used for building LaTeX files using Travis
# A minimal current TL is installed adding only the packages that are
# required

# See if there is a cached version of TL available
export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
if ! command -v texlua > /dev/null; then
  # Obtain TeX Live
  wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  tar -xzf install-tl-unx.tar.gz
  cd install-tl-20*

  # Install a minimal system
  ./install-tl --profile=../texlive/texlive.profile

  cd ..
fi

# Just including texlua so the cache check above works
tlmgr install luatex

# Then you can add one package per line in the texlive_packages file
# We need to change the working directory before including a file
cd "$(dirname "${BASH_SOURCE[0]}")"
tlmgr install $(cat texlive_packages | grep -v -e '^[[:space:]]*$' -e '^#')

# Keep no backups (not required, simply makes cache bigger)
tlmgr option -- autobackup 0

# Update the TL install but add nothing new
tlmgr update --self --all --no-auto-install
```
In `texlive_packages` I've added all the necessary packages to be able to compile the example files:
```bash
# In the case you have to install packages manually, you can use an index of packages like
# http://ctan.mirrors.hoobly.com/systems/texlive/tlnet/archive/
# Or better, check https://www.ctan.org/pkg/some-package to see in which TeX Live package it is contained.
# Or use $ tlmgr info some-package
# Base dependencies and tools to compile
mathtools thmtools babel-dutch latexmk texliveonfly 
# index and bib
imakeidx biblatex biber logreq
# others
stmaryrd xcolor pdfpages eso-pic pgf pgfplots cancel xkeyval 
listings fancyvrb zapfding makecmds epslatex-fr opensans fontaxes csquotes
etoolbox enumitem float booktabs polynom multirow marvosym ulem algorithms 
algorithmicx chngcntr
# For minted
minted fvextra caption upquote lineno xstring framed
# LuaTeX and XeTeX
luaotfload lualatex-math lm-math unicode-math
```
I also moved the comments that were in `texlive_install.sh` in addition to using comments can also have blank lines, more note of the use of `tlmgr info`.
And I modified the file `.travis.yml` to:
```yml
language: generic

# Add distro
dist: bionic

## Comment the following lines if you do not use the minted package
before_install:
 - sudo apt-get install python-pygments
## Comment the following lines if you do not use custom fonts
 - mkdir $HOME/.fonts
 - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
 - fc-cache -f -v

install:
  - source ./texlive/texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR/src/
script:
  # Texliveonfly will download packages automatically
  #- texliveonfly main.tex
  # You can use latexmk to automatically handle bibtex and references (recommended)
  - latexmk -pdf main.tex
  - latexmk -pdf biber-mwe.tex
  - latexmk -e '$pdflatex=q/pdflatex %O -shell-escape %S/' -pdf minted.tex
  - latexmk -lualatex fonts.tex

  # But you could use any other compiler as well instead of latexmk. Example:
#  - pdflatex main.tex
#  - bibtex main
#  - pdflatex main.tex
#  - pdflatex main.tex # Compile twice to fix references

  # You can also pass arguments to texliveonfly:
#  - texliveonfly --arguments='-shell-escape' main.tex
```
And I removed `osfigures` from `main.tex`:
```latex
\usepackage[default]{opensans} % Open Sans typeface
```
My original idea was to reduce the times a little and load only what was necessary without having to modify `.travis.yml` every time I made a change. The complete fork example [travis-ci-latex-pdf
](https://github.com/pablgonz/travis-ci-latex-pdf).
I hope it helps to create a better tutorial...
Greetings

**Comment by PHPirates** [comment]
Thanks, I'm glad you appreciate it! Contributions are welcome, do you want to [fork](https://help.github.com/en/articles/about-forks) and [create a pull request](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) for these changes? Then it is much easier for me to see what exactly the changes are, and it will also be easier to merge them.

At first glance, I'm not sure I understand what you are trying to do with switching on commit messages in the `.travis.yml`: installing python-pygments and copying fonts should take negligible time really, so why take so much trouble for that? When I look in your build history the builds still take around one minute, just as before, so I don't see any improvement?
I also don't really understand why you created a separate lua file for compiling.

Note I'm not saying I don't like the change, but it looks like a lot of extra code especially in the travis yml. Since with this tutorial I'm trying to make things _less_ complicated, I would like to be able to say something like 
"If you want [more customization in ..., or 10 seconds less build time, or whatever is the real advantage of your setup] then pablgonz' setup will be exactly right for you"  :)

**Comment by pablgonz** [comment]
A thousand apologies, for wasting your time, I hadn't read contributing guidelines. After spending several hours playing with `travis` I realized that my initial idea did not affect anything once the cache is created. The usual moral... _"first read the documentation"_. 
The only thing I could notice is that adding `dist: bionic` reduces times between 15 and 20 seconds. I hope that "something" I have written about will help you. 
Thanks again for your work.

**Comment by PHPirates** [comment]
@pablgonz No worries, I'm always interested in new ideas. Yeah the forking/pull request thing holds for all development with git, may be useful to know ;)
Oh that's interesting, I don't know off the top of my head what Travis uses as default distro these days (edit: looks to be xenial) - but it's not unlikely that bionic contains performance improvements. Will try that, thanks.

**Comment by pablgonz** [comment]
I think I understood what is going on, with the test that is executed a false/positive is created, the truth is that it does not cache the files of  `TeXLive`. By adding the line `dist: xenian` or `dist: bionic` in `travis.yml` the problem disappears, apparently the system gets confused when repeating the test downloads everything again. Modifying the `travis.yml` file to this:

```yml
# We test each method for building LaTeX in a separate job.
language: generic

# Add distro
dist: xenial

# This is required to test texlive-docker because it searches for config options in this file
tex-config:
  - build-pattern=src/main.tex,src/mwe.tex
  - packages=xkeyval, collection-latex, collection-langeuropean, exam, amsmath, amscls, mathtools, thmtools, stmaryrd, xcolor, pdfpages, pgf, cancel, hyperref, pgfplots, listings, scalerel, stackengine, etoolbox, listofitems, marvosym, amsfonts, opensans, slantsc, fancyhdr, ulem, algorithms, algorithmicx, float, booktabs, enumitem, polynom, fancyvrb, makecmds, multirow, chngcntr, fvextra, upquote, lineno, ifplatform, xstring, framed, caption, collection-fontsrecommended, minted, pgfgantt, geometry, beamer, translator, environ, trimspaces, imakeidx, graphics, tools, oberdiek

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
    - $HOME/miniconda
    - $HOME/.cache/Tectonic

jobs:
  include:
    # Each - starts a separate job
    - script: travis_retry chmod +x $TRAVIS_BUILD_DIR/test/tectonic-docker-test.sh && $TRAVIS_BUILD_DIR/test/tectonic-docker-test.sh
      name: "Run tectonic-docker-test"
#    - script: travis_retry chmod +x $TRAVIS_BUILD_DIR/test/tectonic-miniconda-test.sh && $TRAVIS_BUILD_DIR/test/tectonic-miniconda-test.sh
#      name: "Run tectonic-miniconda-test"
#    - script: travis_retry chmod +x $TRAVIS_BUILD_DIR/test/texlive-docker-test.sh && $TRAVIS_BUILD_DIR/test/texlive-docker-test.sh
#      name: "Run texlive-docker-test"
#    - script: travis_retry chmod +x $TRAVIS_BUILD_DIR/test/texlive-docker-texliveonfly-test.sh && $TRAVIS_BUILD_DIR/test/texlive-docker-texliveonfly-test.sh
#      name: "Run texlive-docker-texliveonfly"
    - before_install:
        - sudo apt-get install python-pygments
        - mkdir $HOME/.fonts
        - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
        - fc-cache -f -v
      script: travis_retry chmod +x $TRAVIS_BUILD_DIR/test/texlive-test.sh && $TRAVIS_BUILD_DIR/test/texlive-test.sh
      name: "Run texlive-test"
```
or using `dist: bionic` and repeat the test several times, it saves the `TeXLive` cache`.

When comparing the times, using `cache`, the differences are minimal, but there are differences, `xenial texlive` loads a little slower than `bionic texlive` and `xenial tectonic` loads a little faster than `bionic tectonic`, after repeating the test many times (not so many times as to apply the "Law of the great numbers", but enough times) to eliminate the variable "network speed" once the `cache` is created. 
A couple of images after creating the cache and repeating the test:
![xenial](https://user-images.githubusercontent.com/2289461/62439159-e294a000-b718-11e9-8519-09aa99a79b2a.png)
![bionic](https://user-images.githubusercontent.com/2289461/62439160-e294a000-b718-11e9-9cbf-32d595dfab11.png)

Conclusion...I don't know...I've been repeating this for hours and it's not clear to me...but adding `bionic` using `TeXLive` accelerates the start and the process, of course, based on this test.

What is clear to me are two things:
1. It is necessary to remove `osfigures` from the `opensans` package in `main.tex`.
2. `texlive-docker-test` does not work with `dist: bionic` also tries to load `TeXLive 2018` which is already obsolete.

A thousand apologies once again for wasting your time....

Saludos
