### ISSUE TITLE
Test/build all methods

### ISSUE THREAD

**Issue by jason-neal** [PHPirates/travis-ci-latex-pdf#7]
I see you tried a jobs branch would using  the build matrix help?
```
matrix:
    include:
        - env: TEXBUILD=tectonic
        - env: TEXBUILD=pdflatex
        - env: TEXBUILD=tinytex
```

Then have an install script that does the correct things from each .travis.yml file.

I am not sure if it is possible to execute separate portions of the different travis config files

main` .travis-ci.yml`
```
install:   
 # if $TEXBUILD == pdflatex:
          # execute code from  1-tectonic/.travis-ci.yml install:  
 # else if $TEXBUILD == pdflatex:
       # execute code from  2-texlive-pdflatex/.travis-ci.yml  install: 
 # else if $TEXBUILD == pdflatex:
      # execute code from  tinytex/.travis-ci.yml install:
script: 
  #if $TEXBUILD == tectonic:
          # execute code from 1-tectonic/.travis-ci.yml   script:
 # else if $TEXBUILD == pdflatex:
       # execute code from  2-texlive-pdflatex/.travis-ci.yml  script:
 # else if $TEXBUILD == tinytex:
      # execute code from  tinytex/.travis-ci.yml   script:
```
